import * as React from 'react';

import { Enum } from './Enum';
import { EnumMy } from './EnumMy';
import { EnumWrong } from './EnumWrong';

const EnumDemo = () => {
    const value = EnumWrong.HOURS;
    const myValue = EnumMy.HOURS;
    const correctValue = Enum.HOURS;

    return (
        <div style={{ marginTop: '10px' }}>
            <div>Q1 My and project enum implementation, what's difference?</div>
            <div>{value}</div>
            <div>{myValue}</div>
            <div>A1 You copied the sources generated by tsc compiler. Added correct code, see source maps</div>
            <div>{correctValue}</div>
        </div>
    );
};

export default EnumDemo;
